name: 🚀 Deploy DCache-API

on:
  # trigger if pushed to main
  push:
    branches: [ "main" ]

  # manual trigger
  workflow_dispatch:

jobs:
  web-deploy:
    name: FTP Upload
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    # https://github.com/marketplace/actions/sftp-upload
    - name: SFTP Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        uploads: |
          ./api/ => ./www/dcache-api/
        # delete: 'true'
